version: '2'

services:

  elasticsearch:
    image: elasticsearch:latest
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300"
    volumes:
      - /data

  nsqd:
    image: nsqio/nsq:v0.3.6
    hostname: nsqd
    ports:
      - "4150:4150"
      - "4151:4151"
    command: "/bin/sh -c 'while true; do /nsqd -max-msg-size=10024768 -sync-every=1 --mem-queue-size=0 -e2e-processing-latency-percentile=0.90,0.99 -e2e-processing-latency-window-time=10s -statsd-address=statsdaemon:8125 -statsd-interval=10s; done'"
    links:
      - statsdaemon:statsdaemon

  cassandra:
    image: cassandra:2.2
    hostname: cassandra
    ports:
      - "9042"
      - "9160"

  grafana:
    build: images/grafana
    image: raintank/grafana
    hostname: grafana
    depends_on:
      - graphitemon
      - tsdb
      - appsServer
    links:
      - graphitemon:graphitemon
      - tsdb:tsdb
      - appsServer:appsserver
    ports:
      - "80:3000"
    volumes:
      - ./raintank_code/grafana:/go/src/github.com/grafana/grafana
      - ./raintank_code/gitstats-app:/go/src/github.com/grafana/grafana/data/plugins-src/gitstats-app
      - ./logs:/var/log/raintank
      - ./grafana/conf:/etc/grafana/

  statsdaemon:
    image: raintank/statsdaemon
    hostname: statsdaemon
    depends_on:
      - graphitemon
    ports:
      - "8126:8126"
    links:
      - graphitemon:graphitemon

  graphitemon:
    image:  raintank/graphite
    hostname: graphitemon
    ports:
      - "2003:2003"
      - "8000:80"

  metricTank:
    image: raintank/metric_tank
    hostname: metricstank
    depends_on:
      - nsqd
      - elasticsearch
      - statsdaemon
      - cassandra
    ports:
      - "6060"
    links:
      - nsqd:nsqd
      - statsdaemon:statsdaemon
      - cassandra:cassandra
      - elasticsearch:elasticsearch
    volumes:
      - ./logs:/var/log/raintank
      - ./raintank_code/raintank-metric:/go/src/github.com/raintank/raintank-metric

  nsqProbeEventsToElasticsearch:
    image: raintank/nsq_probe_events_to_elasticsearch
    hostname: npee
    depends_on:
      - nsqd
      - elasticsearch
      - statsdaemon
    ports:
      - "6062:6060"
    links:
      - nsqd:nsqd
      - elasticsearch:elasticsearch
      - statsdaemon:statsdaemon
    volumes:
      - ./logs:/var/log/raintank
      - ./raintank_code/raintank-metric:/go/src/github.com/raintank/raintank-metric

  graphiteApi:
    image: raintank/graphite-api
    hostname: graphite
    depends_on:
      - elasticsearch
      - statsdaemon
      - metricTank
    ports:
      - "8888:8888"
    links:
      - elasticsearch:elasticsearch
      - statsdaemon:statsdaemon
      - metricTank:metricstank
    volumes:
      - ./logs:/var/log/raintank

  tsdb:
    image: raintank/tsdb
    hostname: tsdb
    depends_on:
      - nsqd
      - statsdaemon
      - graphiteApi
    ports:
      - "80"
    links:
      - nsqd:nsqd
      - statsdaemon:statsdaemon
      - graphiteApi:graphiteapi
    volumes:
      - ./logs:/var/log/raintank
      - ./raintank_code/raintank-apps:/go/src/github.com/raintank/raintank-apps

  appsServer:
    image: raintank/apps-server
    hostname: appsserver
    depends_on:
      - statsdaemon
    ports:
      - "80"
    links:
      - statsdaemon:statsdaemon
    volumes:
      - ./logs:/var/log/raintank
      - ./raintank_code/raintank-apps:/go/src/github.com/raintank/raintank-apps

  appsAgent:
    image: raintank/apps-agent
    hostname: appsagent
    depends_on:
      - appsServer
      - tsdb
    ports:
      - "8181"
    links:
      - appsServer:appsserver
      - tsdb:tsdb
    volumes:
      - ./logs:/var/log/raintank
      - ./raintank_code/raintank-apps:/go/src/github.com/raintank/raintank-apps