elasticsearch:
  image: library/elasticsearch:latest
  hostname: elasticsearch
  ports:
    - "9200:9200"
    - "9300"
  volumes:
    - /data

rabbitmq:
  image: raintank/rabbitmq
  hostname: rabbitmq
  ports:
    - "5672"
    - "15672:15672"

nsqd:
  image: nsqio/nsq:v0.3.6
  hostname: nsqd
  ports:
    - "4150:4150"
    - "4151:4151"
  command: "/bin/sh -c 'while true; do /nsqd -max-msg-size=10024768 -sync-every=1 --mem-queue-size=0 -e2e-processing-latency-percentile=0.90,0.99 -e2e-processing-latency-window-time=10s -statsd-address=statsdaemon:8125 -statsd-interval=10s; done'"
  links:
    - statsdaemon:statsdaemon

nsqadmin:
  image: nsqio/nsq:v0.3.6
  hostname: nsqadmin
  ports:
    - "4171:4171"
  command: "/nsqadmin --nsqd-http-address=nsqd:4151"
  links:
    - nsqd:nsqd

kafka:
  image: raintank/kafka
  hostname: kafka
  environment:
    ADVERTISED_HOST: kafka
  ports:
    - "2181:2181"
    - "9092:9092"
    - "9999:9999"
  volumes:
    - /tmp/kafka-logs
    - ../logs/zookeeper:/var/log/zookeeper
    - ../logs/supervisor:/var/log/supervisor

kafkaManager:
  image: sheepkiller/kafka-manager
  hostname: kafka-manager
  environment:
          ZK_HOSTS: kafka:2181
          APPLICATION_SECRET: somesalt
  ports:
    - "9000:9000"
  links:
    - kafka:kafka

kafkaOffsetMonitor:
  image: jpodeszwik/kafka-offset-monitor:0.2.1
  hostname: kafka-offset-monitor
  environment:
          ZK: kafka
  ports:
    - "8080:8080"
  links:
    - kafka:kafka


graphitewatcher:
  image: raintank/graphitewatcher
  hostname: watcher
  ports:
    - "6065:6065"
  links:
    - elasticsearch:elasticsearch
    - graphitemon:graphitemon
    - graphiteApi:graphite-api
  volumes:
    - ../logs:/var/log/raintank
    - ../raintank_code/inspect:/go/src/github.com/raintank/inspect

metrictank:
  image: raintank/metrictank
  hostname: metrictank
  ports:
    - "6063:6063"
    - "2002:2003"
  links:
    - nsqd:nsqd
    - statsdaemon:statsdaemon
    - cassandra:cassandra
    - elasticsearch:elasticsearch
    - kafka:kafka
  volumes:
    - ../logs:/var/log/raintank
    - ../raintank_code/metrictank:/go/src/github.com/raintank/metrictank

nsqMetricsToStdout:
  image: raintank/nsq_metrics_to_stdout
  hostname: nms
  links:
    - nsqd:nsqd
  volumes:
    - ../raintank_code/inspect:/go/src/github.com/raintank/inspect

eventtank:
  image: raintank/eventtank
  hostname: npee
  ports:
    - "6062:6060"
  links:
    - nsqd:nsqd
    - elasticsearch:elasticsearch
    - statsdaemon:statsdaemon
  volumes:
    - ../logs:/var/log/raintank
    - ../raintank_code/eventtank:/go/src/github.com/raintank/eventtank

graphitemon:
  image:  raintank/graphite
  hostname: graphitemon
  ports:
    - "2003:2003"
    - "8000:80"

cassandra:
  image: cassandra:3.0.8
  hostname: cassandra
  ports:
    - "9042"
    - "9160"
    - "8888"

mysql:
  image: mysql
  hostname: mysql
  ports:
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: rootpass
    MYSQL_DATABASE: grafana
    MYSQL_USER: grafana
    MYSQL_PASSWORD: password
  volumes:
    - /var/lib/mysql

graphiteApi:
  image: raintank/graphite-api
  hostname: graphite
  ports:
    - "8888:8888"
  links:
    - elasticsearch:elasticsearch
    - statsdaemon:statsdaemon
    - cassandra:cassandra
    - metrictank:metrictank
  volumes:
    - ../logs:/var/log/raintank

worldpingApi:
  image: raintank/worldping_api
  hostname: worldpingapi
  ports:
    - "80:80"
  links:
    - rabbitmq:rabbitmq
    - graphiteApi:graphite-api
    - mysql:mysql
    - elasticsearch:elasticsearch
    - statsdaemon:statsdaemon
    - nsqd:nsqd
  volumes:
    - ../raintank_code/worldping-api:/go/src/github.com/raintank/worldping-api
    - ../logs:/var/log/raintank
    - ./worldping_api/conf:/etc/raintank/

statsdaemon:
  image: raintank/statsdaemon
  hostname: statsdaemon
  ports:
    - "8126:8126"
  links:
    - graphitemon:graphitemon

benchmark:
  image: raintank/benchmark
  hostname: benchmark
  volumes:
    - ../raintank_code/inspect:/go/src/github.com/raintank/inspect
    - ../raintank_code/fakemetrics:/go/src/github.com/raintank/fakemetrics
    - ../logs:/var/log/raintank
    - ../results:/opt/raintank/raintank-tsdb-benchmark/results
  ports:
    - "6764:6764"
  links:
    - statsdaemon:statsdaemon
    - nsqd:nsqd
    - elasticsearch:elasticsearch
    - graphiteApi:graphite-api
    - metrictank:metrictank
    - carbon-relay-ng:carbon-relay-ng
    - kafka:kafka
    - tsdbgw:tsdbgw

grafana:
  image: raintank/grafana
  hostname: grafana
  ports:
    - "3000:3000"
  links:
    - proxy:worldping-api.raintank.io
    - metrictank:metrictank
  volumes:
    - ../raintank_code/plugins:/var/lib/grafana/plugins
    - ../logs:/var/log/raintank

proxy:
  image: raintank/proxy
  hostname: proxy
  ports:
    - "443:443"
  links:
    - worldpingApi:worldpingapi

taskAgent:
  image: raintank/task-agent
  hostname: task-agent
  ports:
    - "8181:8181"
  links:
    - taskServer:task-server
    - tsdbgw:tsdbgw
  volumes:
    - ../raintank_code/raintank-apps/build/bin:/go/bin
    - ../raintank_code/raintank-apps/build/plugins:/var/lib/snap/plugins
    - ../logs:/var/log/raintank

taskServer:
  image: raintank/task-server
  hostname: task-server
  ports:
    - "8082:80"
  links:
    - rabbitmq:rabbitmq
    - statsdaemon:statsdaemon
  volumes:
    - ../raintank_code/raintank-apps/build/bin:/go/bin
    - ../logs:/var/log/raintank

tsdbgw:
  image: raintank/tsdb-gw
  hostname: tsdbgw
  ports:
    - "8081:80"
  links:
    - graphiteApi:graphite-api
    - elasticsearch:elasticsearch
    - statsdaemon:statsdaemon
    - nsqd:nsqd
    - kafka:kafka
  volumes:
    - ../raintank_code/tsdb-gw:/go/src/github.com/raintank/tsdb-gw
    - ../logs:/var/log/raintank

carbon-relay-ng:
  image: raintank/carbon-relay-ng
  hostname: carbon-relay-ng
  ports:
    - "8083:8083"
    - "2013:2013"
  links:
    - graphitemon:graphitemon
    - tsdbgw:tsdbgw
  volumes:
    - ../raintank_code/carbon-relay-ng:/go/src/github.com/graphite-ng/carbon-relay-ng
    - ../logs:/var/log/raintank
  
collectd:
  image: raintank/collectd
  hostname: collectd
  links:
    - graphitemon:graphitemon
    - kafka:kafka
