version: '2'

services:

  taskServer:
    image: raintank/task-server
    hostname: taskserver
    ports:
      - "8081:80"
    external_links:
      - rt_statsdaemon_1:statsdaemon
    volumes:
      - ./logs:/var/log/raintank
      - ./raintank_code/raintank-apps:/go/src/github.com/raintank/raintank-apps

  taskAgent:
    image: raintank/task-agent
    hostname: appsagent
    depends_on:
      - taskServer
    ports:
      - "8181:8181"
    links:
      - taskServer:taskserver
    external_links:
      - rt_tsdb_1:tsdb
    volumes:
      - ./logs:/var/log/raintank
      - ./raintank_code/raintank-apps:/go/src/github.com/raintank/raintank-apps