version: '2'

services:

  elasticsearch:
    image: elasticsearch:latest
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300"
    volumes:
      - /data

  nsqd:
    image: nsqio/nsq:v0.3.6
    hostname: nsqd
    ports:
      - "4150:4150"
      - "4151:4151"
    command: "/bin/sh -c 'while true; do /nsqd -max-msg-size=10024768 -sync-every=1 --mem-queue-size=0 -e2e-processing-latency-percentile=0.90,0.99 -e2e-processing-latency-window-time=10s -statsd-address=statsdaemon:8125 -statsd-interval=10s; done'"
    external_links:
      - rt_statsdaemon_1:statsdaemon

  cassandra:
    image: cassandra:2.2
    hostname: cassandra
    ports:
      - "9042"
      - "9160"

  metricTank:
    image: raintank/metric_tank
    hostname: metricstank
    depends_on:
      - nsqd
      - elasticsearch
      - cassandra
    ports:
      - "6061:6060"
    links:
      - nsqd:nsqd
      - cassandra:cassandra
      - elasticsearch:elasticsearch
    external_links:
      - rt_statsdaemon_1:statsdaemon
    volumes:
      - ../logs:/var/log/raintank
      - ../raintank_code/raintank-metric:/go/src/github.com/raintank/raintank-metric

  nsqProbeEventsToElasticsearch:
    image: raintank/nsq_probe_events_to_elasticsearch
    hostname: npee
    depends_on:
      - nsqd
      - elasticsearch
    ports:
      - "6062:6060"
    links:
      - nsqd:nsqd
      - elasticsearch:elasticsearch
    external_links:
      - rt_statsdaemon_1:statsdaemon
    volumes:
      - ../logs:/var/log/raintank
      - ../raintank_code/raintank-metric:/go/src/github.com/raintank/raintank-metric

  graphiteApi:
    image: raintank/graphite-api
    hostname: graphite
    depends_on:
      - elasticsearch
      - metricTank
    ports:
      - "8888:8888"
    links:
      - elasticsearch:elasticsearch
      - metricTank:metricstank
    external_links:
      - rt_statsdaemon_1:statsdaemon
    volumes:
      - ../logs:/var/log/raintank

  tsdb:
    image: raintank/tsdb
    hostname: tsdb
    depends_on:
      - nsqd
      - graphiteApi
    ports:
      - "8082:80"
    links:
      - nsqd:nsqd
      - graphiteApi:graphiteapi
    external_links:
      - rt_statsdaemon_1:statsdaemon
    volumes:
      - ../logs:/var/log/raintank
      - ../raintank_code/raintank-apps:/go/src/github.com/raintank/raintank-apps
